//
// Autogenerated by Thrift Compiler (0.14.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
if (typeof Int64 === "undefined" && typeof require === "function") {
  const Int64 = require("node-int64");
}

const User = class {
  constructor(args) {
    this.id = null;
    this.name = null;
    this.age = null;
    if (args) {
      if (args.id !== undefined && args.id !== null) {
        this.id = args.id;
      }
      if (args.name !== undefined && args.name !== null) {
        this.name = args.name;
      }
      if (args.age !== undefined && args.age !== null) {
        this.age = args.age;
      }
    }
  }

  read(input) {
    input.readStructBegin();
    while (true) {
      const ret = input.readFieldBegin();
      const ftype = ret.ftype;
      const fid = ret.fid;
      if (ftype == Thrift.Type.STOP) {
        break;
      }
      switch (fid) {
        case 1:
          if (ftype == Thrift.Type.STRING) {
            this.id = input.readString().value;
          } else {
            input.skip(ftype);
          }
          break;
        case 2:
          if (ftype == Thrift.Type.STRING) {
            this.name = input.readString().value;
          } else {
            input.skip(ftype);
          }
          break;
        case 3:
          if (ftype == Thrift.Type.I16) {
            this.age = input.readI16().value;
          } else {
            input.skip(ftype);
          }
          break;
        default:
          input.skip(ftype);
      }
      input.readFieldEnd();
    }
    input.readStructEnd();
    return;
  }

  write(output) {
    output.writeStructBegin("User");
    if (this.id !== null && this.id !== undefined) {
      output.writeFieldBegin("id", Thrift.Type.STRING, 1);
      output.writeString(this.id);
      output.writeFieldEnd();
    }
    if (this.name !== null && this.name !== undefined) {
      output.writeFieldBegin("name", Thrift.Type.STRING, 2);
      output.writeString(this.name);
      output.writeFieldEnd();
    }
    if (this.age !== null && this.age !== undefined) {
      output.writeFieldBegin("age", Thrift.Type.I16, 3);
      output.writeI16(this.age);
      output.writeFieldEnd();
    }
    output.writeFieldStop();
    output.writeStructEnd();
    return;
  }
};

export default User;
